// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/login.tsx";
import * as $4 from "./routes/posts/[id].tsx";
import * as $5 from "./routes/posts/index.tsx";
import * as $6 from "./routes/posts/new.tsx";
import * as $7 from "./routes/signup.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/EditPost.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/login.tsx": $3,
    "./routes/posts/[id].tsx": $4,
    "./routes/posts/index.tsx": $5,
    "./routes/posts/new.tsx": $6,
    "./routes/signup.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/EditPost.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
